apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-inference-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-inference-app
  template:
    metadata:
      labels:
        app: ml-inference-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: ml-inference-app
        image: app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
