apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-inference-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-inference-app
  template:
    metadata:
      labels:
        app: ml-inference-app
    spec:
      containers:
      - name: ml-inference-app
        image: app2:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080