apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ml-inference-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ml-inference-app
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
