apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ml-inference-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ml-inference-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: custom_metric
      target:
        type: AverageValue
        averageValue: 100m
  targetCPUUtilizationPercentage: 50
