apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: your-app-service-monitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: your-app
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
