apiVersion: v1
kind: Service
metadata:
  name: ml-inference-app-service
spec:
  selector:
    app: ml-inference-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
